[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
numRetries = 10 