[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 180
healthcheckInterval = 15
restartPolicy = "on-failure"
numRetries = 10 