[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
restartPolicy = "on-failure"
numRetries = 10

[[cron]]
schedule = "0 12 * * *"  # Run at 12:00 UTC
command = "node src/scripts/updateBattles.js"

[[cron]]
schedule = "0 0 * * *"   # Run at 00:00 UTC
command = "node src/scripts/updateBattles.js" 